pipeline {

    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Source Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/Bikkythecoder/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('python-jenkins-argocd-k8s') {
                    sh '''
                    echo "Building Docker Image..."
                    docker build -t bikkybabu/cicd-e2e:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Push Docker Image') {
    steps {
        dir('python-jenkins-argocd-k8s') {

            withCredentials([
                usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )
            ]) {

                sh '''
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                docker push bikkybabu/cicd-e2e:${IMAGE_TAG}

                docker logout
                '''
            }
        }
    }
}

        stage('Update Kubernetes Manifest') {
            steps {
                dir('python-jenkins-argocd-k8s/deploy') {

                    withCredentials([
                        usernamePassword(
                            credentialsId: 'github-creds',
                            usernameVariable: 'GIT_USERNAME',
                            passwordVariable: 'GIT_PASSWORD'
                        )
                    ]) {

                        sh '''
                        echo "Before Update:"
                        cat deploy.yaml

                        sed -i '' 's|image: .*|image: bikkybabu/cicd-e2e:12|g' deploy.yaml

                        echo "After Update:"
                        cat deploy.yaml

                        git config user.name "Jenkins"
                        git config user.email "jenkins@example.com"

                        git add deploy.yaml

                        git commit -m "Updated image to build ${IMAGE_TAG}" || echo "No changes to commit"

                        git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Bikkythecoder/Jenkins-Zero-To-Hero.git HEAD:main
                        '''
                    }
                }
            }
        }
    }
}
