pipeline {

    agent {
        docker {
            image 'bikkybabu/maven-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage('Build and Test') {
            steps {
                sh '''
                    cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
                    mvn clean package
                '''
            }
        }


        stage('Static Code Analysis') {

            environment {
                SONAR_URL = "http://host.docker.internal:9000"
            }

            steps {

                withCredentials([
                    string(credentialsId: 'sonarqube',
                    variable: 'SONAR_AUTH_TOKEN')
                ]) {

                    sh '''
                        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app

