pipeline {
    agent any

    environment {
        PATH = "/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    }

    stages {
        stage('Docker Test') {
            steps {
                sh 'docker --version'
                sh 'docker pull node:16-alpine'
            }
        }
    }
}
